### ISSUE TITLE
get_link_target_path() error

### ISSUE THREAD

**Issue by stuta** [sonoro1234/luafilesystem#2]
In OSX 10.14 read returns 18446744073709551615ULL so loop will run until it ends in error.

Fix suggestion, I don't know if this is good:
```lua
if read < size or read > math.huge then
  return ffi_str(buf)
end
```

**Comment by stuta** [comment]
That fix is not good, in 32 bit luajit read is 4294967295 that is smaller than math.huge. Maybe we could use read > 10^9 but this does not seem as good fix.

**Comment by sonoro1234** [comment]
I cant test macos but `'unsigned long readlink(const char *path, char *buf, size_t bufsize);'` should be
`ssize_t readlink(const char *path, char *buf, size_t bufsize);` for getting a signed return allowing for -1 as error

Does this solve the issue?

**Comment by stuta** [comment]
Yes, that fixes it. 
Code returns errno(), but it is not used anywhere.
Why there is a loop in this code? And if loop is needed then should it be ```if read <= size then```?

**Comment by sonoro1234** [comment]
Just pushed correction (@spacewander may wish to chage it also)

Now working in another way to get size.
Just done in https://github.com/sonoro1234/luafilesystem/tree/readlink
I am not able to test it now. @stuta does it work?

**Comment by spacewander** [comment]
@sonoro1234 
Thank you for your notification!
I will cherry-pick your change once @stuta confirms that the fix works well.

**Comment by stuta** [comment]
Hello. Like I wrote ssize_t fixes the problem. I don't know why there is that ```while true do``` loop if MAXPATH is correct. If loop is necessary (why?) this 
```lua
if read < size then
  return ffi_str(buf)
end
```

should be 

```lua
if read <= size then
  return ffi_str(buf)
end
```

**Comment by sonoro1234** [comment]
Loop was used to double size each time until read < size, if size== read there is no space for last null byte which is not appended by readlink (https://linux.die.net/man/2/readlink)

In my last commit there no while loop but instead size is calculated calling readlink twice: https://github.com/sonoro1234/luafilesystem/blob/readlink/lfs_ffi.lua#L1235

As I said, I cant try it because i dont have macos, so I was waiting until you try it in order to merge it on unicode branch.

**Comment by stuta** [comment]
Error: stat_type is used before it is declared.

**Comment by stuta** [comment]
If I move stat_type declaration before function the there is error: ```wrong number of arguments for function call```. This comes from lstat_func(link_path.statbuf), it needs 2 arguments: ```int lstat64(const char *path, lfs_stat *buf);```

**Comment by stuta** [comment]
Function lstat_func() like other C function calls needs path as C-string. Now link_path is normal Lua string. Also when code works then buf[size] = 0 is not needed, it is faster to ```return ffi_str(buf, statbuf.st_size) ```.

**Comment by stuta** [comment]
Simplest and fastest option is to trust MAXPATH and do not call lstat_func() at all and do not loop at all.

**Comment by stuta** [comment]
This is the fastest way to do this. No expensive memory allocation needed. Because calls to get_link_target_path() do not handle second return parameter then there's no point in returning it. And in server environment calls to error() function is never allowed and here it is not needed.

```lua
local link_target_buf = ffi.new('char[?]', MAXPATH)
function get_link_target_path(link_path)
  local read = lib.readlink(link_path, link_target_buf, MAXPATH)
  if read == -1 then
    return nil
  end
  return ffi_str(link_target_buf)
end
```

**Comment by sonoro1234** [comment]
Just pushed get_link_target_path correction to unicode branch
